language: Swift
osx_image: xcode12.1
xcode_project: TextFieldsCatalog.xcodeproj
xcode_scheme: TextFieldsCatalog
before_install:
  - gem install xcpretty -N
  - make init
script:
  - set -o pipefail
  - xcodebuild clean build -sdk iphonesimulator -workspace TextFieldsCatalog.xcworkspace -scheme TextFieldsCatalog CODE_SIGNING_REQUIRED=NO | xcpretty -c
  - swift build -v -Xswiftc "-sdk" -Xswiftc "xcrun --sdk iphonesimulator --show-sdk-path" -Xswiftc "-target" -Xswiftc "x86_64-apple-ios13.0-simulator"
