name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'
    types: [ opened, edited ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: CocoaPods
      run: |
        gem install xcpretty -N
        make init
    - name: Force xcode 12
      run: |
        sudo xcode-select -switch /Applications/Xcode_12.0.1.app
    - name: Build
      run: |
        make build
    - name: Test
      run: |
        make test
    - name: documentation
      if: github.ref == 'refs/heads/master'
      run: |
        make doc
    - name: Commit changes
      uses: EndBug/add-and-commit@v4
      with:
        author_name: chausovSurfStudio
        author_email: chausov@surfstudio.ru
        message: "Updates for documentation"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
